version: 2.1

jobs:
  clone-cli:
    docker:
      - image: cimg/go:1.22
    resource_class: small
    steps:
      - checkout
      - run: go mod download
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-tests:
    docker:
      - image: cimg/go:1.22
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          command: make test
          no_output_timeout: 2m

workflows:
  test:
    jobs:
      - clone-cli
      - run-tests:
          requires: [clone-cli]
